# Copyright Louis Dionne 2015
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

os:
  - MinGW

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build_script:
  - cd build && cmake .. && cmake --build . --target check
