# Copyright Louis Dionne 2015
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

shallow_clone: true

os:
  - Visual Studio 2015
  - Visual Studio 2015 CTP
  - Visual Studio 2015 CTP 6
  - Visual Studio 2015 Preview
  - Visual Studio 2015 RC
  - MinGW

build:
  verbosity: detailed

configuration:
  - Debug


install:
  - ps: echo "Downloading Clang 3.7"
  - ps: Start-FileDownload "http://llvm.org/releases/3.7.0/LLVM-3.7.0-win64.exe" -FileName LLVM-3.7.0-win64.exe
  - ps: dir
  - ps: echo "Installing Clang 3.7"
  - ps: 7z x LLVM-3.7.0-win64.exe -y -o"C:\projects\hana\clang37"
  # - ps: Start-Process -FilePath "C:\projects\hana\clang37-installer.exe"
  - ps: dir
  - ps: cd "C:\projects\hana\clang37"
  - ps: dir
  - ps: cd "C:\projects\hana\clang37\LLVM"
  - ps: dir
  - ps: cd "C:\projects\hana\clang37\LLVM\msbuild-bin"
  - ps: dir


build_script:
  - cd C:\projects\hana
  - mkdir build
  - cd build
  - cmd: cmake .. -T LLVM-vs2014 -DCMAKE_CXX_COMPILER="C:\\projects\\hana\\clang37\\msbuild-bin\\cl.exe" -G "Visual Studio 14 2015 Win64"
  # - cmake .. -DCMAKE_CXX_COMPILER="C:\\projects\\hana\\$_OUTDIR\\bin\\clang++.exe"
  # - cmake --build . --target check
