# Copyright Louis Dionne 2015
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

shallow_clone: true

os:
  - MinGW

build:
  verbosity: detailed

configuration:
  - Debug


before_build:
  - which clang
  - which clang++
  - which clang++-3.7
  - env

build_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=clang++-3.7
  - cmake --build . --target check
