# Copyright Louis Dionne 2015
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

shallow_clone: true

os:
  - MinGW

build:
  verbosity: detailed

configuration:
  - Debug


install:
  - ps: >-
      echo "Downloading Clang 3.7"
      Start-FileDownload "http://llvm.org/releases/3.7.0/LLVM-3.7.0-win64.exe" -FileName clang-37.7z

      echo "Extracting Clang 3.7"
      7z x clang-37.7z -y -o"C:\projects\hana\" clang-37

      dir


build_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER="C:\projects\hana\clang-37\bin\clang++.exe"
  - cmake --build . --target check
